import fs from 'node:fs';
import path from 'node:path';
import { root } from './mcp.mjs';
const directory = path.join(root, 'doc/public/examples/tutorials');
const definitions = [
  ['structural','Structural mechanics','Structural cantilever','The shipped [`block.stp`](/guide/cad-mode) is 3 × 4 × 5 mm. Scale it sixfold along X to make an 18 mm long cantilever. Fix `face-3` (the −X end) and apply 100 kPa downward pressure on `face-1` (the −Z broad face). The model uses E = 210 GPa, ν = 0.3 and a 0.8 mm tetrahedral mesh; density is unused in this static example.','DISPLACEMENT z is −0.000589 mm at the free corner; the Euler–Bernoulli reference is −0.000600 mm. The maximum relative displacement error is 1.79%, within the 25% coarse-mesh tutorial tolerance. Select \`VON_MISES_STRESS\` to see the stress field.','m (convert from CAD mm)','18 × 4 × 5 mm (0.018 × 0.004 × 0.005 m); block.stp scaled by [6,1,1]; body Solid; Support face-3; Load face-1','analysisType non_linear; end time 1 s; Δt 0.125 s; 8 frames; 210 GPa; ν 0.3; pressure 100 kPa'],
  ['fluid','Fluid dynamics','Slip-wall channel','Create a 4 × 1 m planar XY rectangle (CAD-native dimensions 4000 × 1000 mm). Name its face `Domain`, x = 0 edge `Left`, x = 4 edge `Right`, and the two y edges `Walls`. Use a 200 mm global mesh size (0.2 m after export). Set the Newtonian 2D material to density 1000 kg/m³ and dynamic viscosity 0.001 Pa·s.','At t = 2 s, the velocity is 1 m/s in +X across the channel. Inlet and outlet fluxes are each 1 m²/s per metre of depth; their measured difference is zero. Outlet pressure is 0 Pa.','m','4 × 1 m XY; face Domain; edges Left, Right, Walls','Δt 0.1 s; end 2 s; 20 frames; inlet 1 m/s +X; outlet 0 Pa; slip walls; ρ 1000 kg/m³; μ 0.001 Pa·s'],
  ['thermal','Convection-diffusion','Stationary heat conduction','Use the 3 × 4 × 5 mm `block.stp` as a solid. Name `solid-0` Domain, `face-3` Cold (−X), and `face-5` Hot (+X). Mesh with 0.8 mm tetrahedra and export to metres. Assign conductivity 1 W/(m·K), density 1000 kg/m³, and specific heat 1000 J/(kg·K).','The generated stationary Laplacian solve gives 300 K on the cold end and 400 K on the hot end. The maximum difference from the linear temperature profile is 0.000019 K.','mm → m','3 × 4 × 5 mm block; body Domain; ends Cold (300 K) / Hot (400 K)','Stationary; time value 1 s; conductivity 1 W/(m·K); density 1000 kg/m³; specific heat 1000 J/(kg·K)'],
  ['potential-flow','Potential flow','Uniform potential flow','Create the same 4 × 1 m planar XY rectangle and 0.2 m mesh. Name its face Domain and all four edges Boundary. Assign Domain as the fluid region and Boundary as the far field. Set incompressible formulation, angle of attack 0 rad, Mach infinity 0.03, and sound speed 340 m/s. No material assignment is needed.','The imposed free-stream speed is 10.2 m/s. The maximum elementwise error in the gradient of `VELOCITY_POTENTIAL` compared with [10.2, 0] m/s is 0.000033 m/s.','m','4 × 1 m XY; face Domain; outer edges Boundary','Incompressible; angle 0 rad; Mach 0.03; sound speed 340 m/s; output `VELOCITY_POTENTIAL`'],
  ['shallow-water','Shallow water','Still-water basin','Create the 4 × 1 m planar XY rectangle (never mesh a solid skin for this 2D case). Name its face Domain and all four edges Boundary. Use a 0.2 m mesh; material Manning coefficient 0.01. Set a flat topography `z(x,y) = 0`, initialize `HEIGHT = 1 m`, and apply slip to Boundary.','At t = 0.125 s, the basin retains 1 m depth. Momentum is below 3 × 10⁻¹⁵ m²/s, and the computed water volume is 4.000000 m³ (error below 10⁻¹⁵ m³).','m','4 × 1 m XY; face Domain; outer edges Boundary','Δt 0.015625 s; end 0.125 s; flat topography; initial height 1 m; gravity 9.81 m/s²; Manning 0.01']
];
for (const [id,domain,title,geometry,result,units,geometryTable,physicsTable] of definitions) {
 const base=`/examples/tutorials/${id}`;
 const report=JSON.parse(fs.readFileSync(path.join(directory,id,'verification.json'),'utf8'));
 const figures=`![CAD geometry and named parts](/screenshots/tutorial-${id}-geometry.png)\n\n![Problemtype setup](/screenshots/tutorial-${id}-setup.png)\n\n![Solver result viewed in KKSS](/screenshots/tutorial-${id}-results.png)`;
 const common=`## Create the model and mesh\n\n${geometry}\n\n1. In CAD mode, select the **Rectangle** sketch operation (or open the supplied block fixture for the solid cases). Enter the stated dimensions in CAD millimetres. For a planar face use center **(2000, 500, 0) mm**, normal **(0, 0, 1)** and up **(1, 0, 0)**.\n2. Under **Parts**, name the face and edges exactly as shown. Use the entity tree and selection highlights to identify edges; on the supplied block use the listed face ids.\n3. Under **FE Mesh**, use Gmsh, dimension ${id==='structural'||id==='thermal'?'3D':'2D'}, first order, size min/max **${id==='structural'||id==='thermal'?'0.8':'200'} mm**. Choose **MDPA Elements**, export units **${units}**, and export as \`mesh.mdpa\`.\n4. Open the exported file in Post-Processing. The Problemtype section is populated from the mesh’s named SubModelParts. Select **${domain}** and enter the case setup below.\n\n## Set up, generate and run\n\n| Setting | Value |\n|---|---|\n| Geometry and SubModelParts | ${geometryTable} |\n| Problemtype values and physics | ${physicsTable} |\n| Python | Point **Settings → Simulation → kratos.pythonPath** at a Python environment that imports Kratos Multiphysics and **${domain==='Structural mechanics'?'StructuralMechanicsApplication':domain==='Fluid dynamics'?'FluidDynamicsApplication':domain==='Convection-diffusion'?'ConvectionDiffusionApplication':domain==='Potential flow'?'CompressiblePotentialFlowApplication':'ShallowWaterApplication'}** |\n\nClick **Generate case files**. This writes \`ProjectParameters.json\`, the materials file (when used), and \`MainKratos.py\` beside the mesh. Inspect generation warnings under the Problemtype panel. Click **Run case**; the embedded terminal shows solver output. The run record and log are saved alongside the case. A failed import usually means the selected Python environment lacks the named Kratos application.\n\nWhen the run finishes, click **Open results**. In the VTK tab, click **Field**, select the listed field, and use the timeline to choose a step. The values below came from the verified final frame.\n\n## Verified result\n\n${result}\n\nVerification used Python ${report.python}, Kratos ${report.kratos}, two OpenMP threads, ${report.nodes} nodes and ${report.elements} cells. The run wrote ${report.frames} output frame(s) through t = ${report.end_time} s. [Download this runnable case](${base}.zip); the folder contains the CAD source, edit/parts/mesh sidecars, generated case, VTK output and SHA-256 provenance. Downloaded cases are starting points: rerunning overwrites their generated outputs.\n\n${figures}\n`;
 fs.writeFileSync(path.join(root,'doc/guide',`tutorial-${id}.md`),`# ${title}\n\n**${domain}.** This walkthrough starts from geometry and ends with a solver-produced field. Lengths, time, mass and temperature use SI after CAD mesh export unless the table says mm. Follow the steps with the built-in example or download the complete case.\n\n${common}`);
}
const landing=`# Geometry to results\n\nThese five tutorials join the CAD and mesh guides into one complete Kratos workflow: make or import geometry, preserve named regions in an MDPA mesh, configure a built-in Problemtype, run a solver and inspect its VTK fields. Each worked case was run with Kratos 10.4.3 and is downloadable with its solver-produced results and provenance.\n\n| Physics | Worked case | Check |\n|---|---|---|\n| Structural mechanics | [Cantilever](tutorial-structural) | Free-end displacement and von Mises stress |\n| Fluid dynamics | [Slip-wall channel](tutorial-fluid) | Uniform velocity and balanced inlet/outlet flux |\n| Convection-diffusion | [Stationary heat conduction](tutorial-thermal) | Linear 300–400 K profile |\n| Potential flow | [Uniform flow](tutorial-potential-flow) | Potential gradient equals free-stream velocity |\n| Shallow water | [Still-water basin](tutorial-shallow-water) | Depth, momentum and volume conservation |\n\nStart from [CAD mode](cad-mode) and [mesh mode](mesh-mode) if you need a tour of either viewer. For a ready-made MDPA-only case that skips geometry, see [Worked Kratos Cases](tutorial-kratos-examples). For a prompted walkthrough using the chat tools, see [Using the AI assistant](tutorial-ai-simulation).\n\n## One workflow for every case\n\n1. Create or open geometry in Pre-Processing; make named Parts for bodies and boundaries.\n2. Generate a first-order Gmsh mesh and export **MDPA Elements**. Use metres for the planar examples; for the supplied millimetre STEP model choose the export-unit conversion stated in its tutorial.\n3. Open the MDPA in Post-Processing, choose a built-in Problemtype, assign each condition and material to its named SubModelPart, and select VTK output.\n4. Set \`kratos.pythonPath\` to a local Python that imports Kratos and the relevant application. KKSS does not bundle Kratos. **Generate case files**, check \`ProjectParameters.json\`, then **Run case** in the embedded terminal.\n5. **Open results**, choose a field from the Field panel, and inspect its range and time steps. A successful process exit alone does not establish numerical correctness; each worked case includes a separate physical check.\n\nFor the full input deck, VTK timeline and SHA-256 file manifest, [download all five cases](/examples/tutorials/tutorial-cases.zip) or download one case from its page. They are tutorial checks with documented tolerances, not formal solver certification.\n`;
fs.writeFileSync(path.join(root,'doc/guide/tutorial-geometry-to-results.md'),landing);
