import fs from 'node:fs';
import path from 'node:path';
import { root } from './mcp.mjs';
const directory = path.join(root, 'doc/public/examples/tutorials');
const definitions = [
  ['structural','Structural mechanics','Structural cantilever','The shipped [`block.stp`](/guide/cad-mode) is 3 × 4 × 5 mm. Scale it sixfold along X to make an 18 mm long cantilever. Fix `face-3` (the −X end) and apply 100 kPa downward pressure on `face-1` (the −Z broad face). The model uses E = 210 GPa, ν = 0.3 and a 0.8 mm tetrahedral mesh; density is unused in this static example.','DISPLACEMENT z is −0.000589 mm at the free corner; the Euler–Bernoulli reference is −0.000600 mm. The maximum relative displacement error is 1.79%, within the 25% coarse-mesh tutorial tolerance. In **Field**, click **TOP** on the orientation cube (or press `3`) to see the X–Z bending plane, enable **Deformed**, set **Deform by** to `DISPLACEMENT`, and use **Warp scale** 1000× to make the sub-micron deflection visible; this scale changes only the display. Select `VON_MISES_STRESS` to inspect the stress field.','m (convert from CAD mm)','18 × 4 × 5 mm (0.018 × 0.004 × 0.005 m); block.stp scaled by [6,1,1]; body Solid; Support face-3; Load face-1','analysisType non_linear; end time 1 s; Δt 0.125 s; 8 frames; 210 GPa; ν 0.3; pressure 100 kPa'],
  ['fluid','Fluid dynamics','Laminar flow around an obstacle','Create a 2.0 × 0.6 m planar XY channel (CAD dimensions 2000 × 600 mm) with a 32-sided circular obstacle of radius 60 mm centered at (500, 300) mm. Import the [SVG sketch recipe](/examples/tutorials/fluid/obstacle-channel.svg), then select its four outer edges and 32 obstacle edges and build one face with the inner loop as a hole. Name the face `Domain`, x = 0 `Inlet`, x = 2000 mm `Outlet`, y = 0 and y = 600 mm `Walls`, and the hole loop `Obstacle`. Use a 2D first-order mesh, global min/max sizes 15/70 mm, and grade around Obstacle from 12 mm at its wall to 60 mm at 350 mm distance (12 mm through the first 25 mm). Export to metres. Set the Newtonian 2D material to density 1000 kg/m³ and dynamic viscosity 0.6 Pa·s; with inlet speed 0.1 m/s this gives Reynolds number 20 based on the 120 mm obstacle diameter.','At t = 5 s, the near-wake sample has a minimum axial velocity of −0.00475046 m/s against the +0.1 m/s inlet, and 32 obstacle boundary nodes satisfy no-slip exactly. Pressure ranges from −7.23421 to 9.28020 Pa with the outlet fixed at 0 Pa. Inlet/outlet fluxes are 0.0600000020 and 0.0600000018 m²/s per metre of depth (difference 2.40 × 10⁻¹⁰ m²/s). The acceptance limits are a near-wake velocity deficit ≥ 0.025 m/s, pressure range ≥ 0.05 Pa, no-slip speed ≤ 2 × 10⁻⁵ m/s, and flux imbalance ≤ 0.001 m²/s.','m (CAD mm → m)','2.0 × 0.6 m XY; face Domain; edge parts Inlet, Outlet, Walls; 32-edge hole Obstacle; 945 nodes; 1766 triangles','Δt 0.1 s; end 5 s; 50 steps + initial frame; inlet 0.1 m/s +X; outlet 0 Pa; slip walls; no-slip obstacle; ρ 1000 kg/m³; μ 0.6 Pa·s; Re 20'],
  ['thermal','Convection-diffusion','Stationary heat conduction','Use the 3 × 4 × 5 mm `block.stp` as a solid. Name `solid-0` Domain, `face-3` Cold (−X), and `face-5` Hot (+X). Mesh with 0.8 mm tetrahedra and export to metres. Assign conductivity 1 W/(m·K), density 1000 kg/m³, and specific heat 1000 J/(kg·K).','The generated stationary Laplacian solve gives 300 K on the cold end and 400 K on the hot end. The maximum difference from the linear temperature profile is 0.000019 K.','mm → m','3 × 4 × 5 mm block; body Domain; ends Cold (300 K) / Hot (400 K)','Stationary; time value 1 s; conductivity 1 W/(m·K); density 1000 kg/m³; specific heat 1000 J/(kg·K)'],
  ['potential-flow','Potential flow','Uniform potential flow','Create the same 4 × 1 m planar XY rectangle and 0.2 m mesh. Name its face Domain and all four edges Boundary. Assign Domain as the fluid region and Boundary as the far field. Set incompressible formulation, angle of attack 0 rad, Mach infinity 0.03, and sound speed 340 m/s. No material assignment is needed.','The imposed free-stream speed is 10.2 m/s. The maximum elementwise error in the gradient of `VELOCITY_POTENTIAL` compared with [10.2, 0] m/s is 0.000033 m/s.','m','4 × 1 m XY; face Domain; outer edges Boundary','Incompressible; angle 0 rad; Mach 0.03; sound speed 340 m/s; output `VELOCITY_POTENTIAL`'],
  ['shallow-water','Shallow water','Still-water basin','Create the 4 × 1 m planar XY rectangle (never mesh a solid skin for this 2D case). Name its face Domain and all four edges Boundary. Use a 0.2 m mesh; material Manning coefficient 0.01. Set a flat topography `z(x,y) = 0`, initialize `HEIGHT = 1 m`, and apply slip to Boundary.','At t = 0.125 s, the basin retains 1 m depth. Momentum is below 3 × 10⁻¹⁵ m²/s, and the computed water volume is 4.000000 m³ (error below 10⁻¹⁵ m³).','m','4 × 1 m XY; face Domain; outer edges Boundary','Δt 0.015625 s; end 0.125 s; flat topography; initial height 1 m; gravity 9.81 m/s²; Manning 0.01']
];
for (const [id,domain,title,geometry,result,units,geometryTable,physicsTable] of definitions) {
 const base=`/examples/tutorials/${id}`;
 const report=JSON.parse(fs.readFileSync(path.join(directory,id,'verification.json'),'utf8'));
 const fieldFigures=id==='structural'
   ? `![Solver result viewed in KKSS](/screenshots/tutorial-structural-results.png)\n\n![Displacement field on the deformed cantilever at 1000× warp scale](/screenshots/tutorial-structural-deformed.png)\n\n![Von Mises stress field on the deformed cantilever](/screenshots/tutorial-structural-stress.png)`
   : id==='fluid'
   ? `![Velocity wake behind the obstacle in KKSS](/screenshots/tutorial-fluid-results.png)\n\n![Pressure around the obstacle in KKSS](/screenshots/tutorial-fluid-pressure.png)`
   : `![Solver result viewed in KKSS](/screenshots/tutorial-${id}-results.png)`;
 const figures=`![CAD geometry and named parts](/screenshots/tutorial-${id}-geometry.png)\n\n![Problemtype setup](/screenshots/tutorial-${id}-setup.png)\n\n${fieldFigures}`;
 const cadSteps=id==='fluid'
   ? `1. Open \`cad/examples/BREP/blank.brep\` in CAD mode. Choose **File → Import SVG…** and open [\`obstacle-channel.svg\`](/examples/tutorials/fluid/obstacle-channel.svg). The recipe creates a 2000 × 600 mm channel and a 32-segment, 60 mm-radius obstacle centered at (500, 300) mm. Imported world coordinates are x = 0…2000 mm and y = 0…600 mm.\n2. Switch to **Line** selection and select both loops. Choose **GEOMETRY → 2D → Surface → Build** to form one flat face with the inner loop as a hole. Confirm the preview shows one face with an opening.\n3. Under **Parts**, name the face \`Domain\`; name x = 0 \`Inlet\`, x = 2000 mm \`Outlet\`, the y edges \`Walls\`, and the inner 32 edges \`Obstacle\`. Use **Surf** selection for the face and **Line** selection for boundaries.\n4. Under **FE Mesh**, choose Gmsh, 2D, first order, global size min/max **15/70 mm**. In the \`Obstacle\` Part's **Grade** controls set size at wall **12 mm**, size far **60 mm**, distance near **25 mm**, and distance far **350 mm**. Choose **MDPA Elements**, export units **m**, and export as \`mesh.mdpa\`. This is a planar XY face mesh with a hole, not the surface mesh of a solid.`
   : `1. In CAD mode, select the **Rectangle** sketch operation (or open the supplied block fixture for the solid cases). Enter the stated dimensions in CAD millimetres. For a planar face use center **(2000, 500, 0) mm**, normal **(0, 0, 1)** and up **(1, 0, 0)**.\n2. Under **Parts**, name the face and edges exactly as shown. Use the entity tree and selection highlights to identify edges; on the supplied block use the listed face ids.\n3. Under **FE Mesh**, use Gmsh, dimension ${id==='structural'||id==='thermal'?'3D':'2D'}, first order, size min/max **${id==='structural'||id==='thermal'?'0.8':'200'} mm**. Choose **MDPA Elements**, export units **${units}**, and export as \`mesh.mdpa\`.`;
 const exportStep=id==='fluid'?'5':'4';
 const solverOutput=id==='fluid'?'2D monolithic VMS; maximum 20 iterations; VTK each 0.1 s step with `VELOCITY` and `PRESSURE`':id==='structural'?'non-linear static mechanics; 8 frames; VTK `DISPLACEMENT` and `VON_MISES_STRESS`':'built-in solver and its documented VTK fields';
 const common=`## Create the model and mesh\n\n${geometry}\n\n${cadSteps}\n${exportStep}. Open the exported file in Post-Processing. The Problemtype section is populated from the mesh’s named SubModelParts. Select **${domain}** and enter the case setup below.\n\n## Set up, generate and run\n\n| Setting | Value |\n|---|---|\n| Geometry and SubModelParts | ${geometryTable} |\n| Problemtype values and physics | ${physicsTable} |\n| Solver/output | ${solverOutput} |\n| Python | Point **Settings → Simulation → kratos.pythonPath** at a Python environment that imports Kratos Multiphysics and **${domain==='Structural mechanics'?'StructuralMechanicsApplication':domain==='Fluid dynamics'?'FluidDynamicsApplication':domain==='Convection-diffusion'?'ConvectionDiffusionApplication':domain==='Potential flow'?'CompressiblePotentialFlowApplication':'ShallowWaterApplication'}** |\n\nClick **Generate case files**. This writes \`ProjectParameters.json\`, the materials file (when used), and \`MainKratos.py\` beside the mesh. Inspect generation warnings under the Problemtype panel. Set the interpreter through **Settings → Simulation → kratos.pythonPath**, then use the Home screen's **Check environment** action to confirm the required application is available. Click **Run case**; the embedded terminal shows solver progress and diagnostics. A failed import usually means the selected Python environment lacks the named Kratos application.\n\nWhen the run finishes, click **Open results**. In the VTK tab, click **Field**, select the listed field, and use the timeline to choose the final step. The values below came from the verified final frame.\n\n## Verified result\n\n${result}\n\nVerification used Python ${report.python}, Kratos ${report.kratos}, two OpenMP threads, ${report.nodes} nodes and ${report.elements} cells. The run wrote ${report.frames} output frame(s) through t = ${report.end_time} s. [Download this runnable case](${base}.zip); the folder contains the CAD source, sketch SVG, edit/parts/mesh sidecars, generated case, VTK output and SHA-256 provenance. Downloaded cases are starting points: rerunning overwrites their generated outputs.\n\n${figures}\n`;
 fs.writeFileSync(path.join(root,'doc/guide',`tutorial-${id}.md`),`# ${title}\n\n**${domain}.** This walkthrough starts from geometry and ends with a solver-produced field. Lengths, time, mass and temperature use SI after CAD mesh export unless the table says mm. Follow the steps with the built-in example or download the complete case.\n\n${common}`);
}
const landing=`# Geometry to results\n\nThese five tutorials join the CAD and mesh guides into one complete Kratos workflow: make or import geometry, preserve named regions in an MDPA mesh, configure a built-in Problemtype, run a solver and inspect its VTK fields. Each worked case was run with Kratos 10.4.3 and is downloadable with its solver-produced results and provenance.\n\n| Physics | Worked case | Check |\n|---|---|---|\n| Structural mechanics | [Cantilever](tutorial-structural) | Deformed shape, free-end displacement and von Mises stress |\n| Fluid dynamics | [Laminar obstacle flow](tutorial-fluid) | Resolved wake, no-slip obstacle, pressure variation and balanced flux |\n| Convection-diffusion | [Stationary heat conduction](tutorial-thermal) | Linear 300–400 K profile |\n| Potential flow | [Uniform flow](tutorial-potential-flow) | Potential gradient equals free-stream velocity |\n| Shallow water | [Still-water basin](tutorial-shallow-water) | Depth, momentum and volume conservation |\n\nStart from [CAD mode](cad-mode) and [mesh mode](mesh-mode) if you need a tour of either viewer. For a ready-made MDPA-only case that skips geometry, see [Worked Kratos Cases](tutorial-kratos-examples). For a prompted walkthrough using the chat tools, see [Using the AI assistant](tutorial-ai-simulation).\n\n## One workflow for every case\n\n1. Create or open geometry in Pre-Processing; make named Parts for bodies and boundaries.\n2. Generate a first-order Gmsh mesh and export **MDPA Elements**. Use metres for the planar examples; for the supplied millimetre STEP model choose the export-unit conversion stated in its tutorial.\n3. Open the MDPA in Post-Processing, choose a built-in Problemtype, assign each condition and material to its named SubModelPart, and select VTK output.\n4. Set \`kratos.pythonPath\` to a local Python that imports Kratos and the relevant application. KKSS does not bundle Kratos. **Generate case files**, check \`ProjectParameters.json\`, then **Run case** in the embedded terminal.\n5. **Open results**, choose a field from the Field panel, and inspect its range and time steps. A successful process exit alone does not establish numerical correctness; each worked case includes a separate physical check.\n\nFor the full input deck, VTK timeline and SHA-256 file manifest, [download all five cases](/examples/tutorials/tutorial-cases.zip) or download one case from its page. They are tutorial checks with documented tolerances, not formal solver certification.\n`;
fs.writeFileSync(path.join(root,'doc/guide/tutorial-geometry-to-results.md'),landing);
